// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.27.3
// source: load_generation_system_v1.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AttackRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*AttackRequest_Handshake
	//	*AttackRequest_Acknowledge
	Request       isAttackRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttackRequest) Reset() {
	*x = AttackRequest{}
	mi := &file_load_generation_system_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttackRequest) ProtoMessage() {}

func (x *AttackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_load_generation_system_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttackRequest.ProtoReflect.Descriptor instead.
func (*AttackRequest) Descriptor() ([]byte, []int) {
	return file_load_generation_system_v1_proto_rawDescGZIP(), []int{0}
}

func (x *AttackRequest) GetRequest() isAttackRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *AttackRequest) GetHandshake() *Handshake {
	if x != nil {
		if x, ok := x.Request.(*AttackRequest_Handshake); ok {
			return x.Handshake
		}
	}
	return nil
}

func (x *AttackRequest) GetAcknowledge() *Acknowledge {
	if x != nil {
		if x, ok := x.Request.(*AttackRequest_Acknowledge); ok {
			return x.Acknowledge
		}
	}
	return nil
}

type isAttackRequest_Request interface {
	isAttackRequest_Request()
}

type AttackRequest_Handshake struct {
	Handshake *Handshake `protobuf:"bytes,1,opt,name=handshake,proto3,oneof"`
}

type AttackRequest_Acknowledge struct {
	Acknowledge *Acknowledge `protobuf:"bytes,2,opt,name=acknowledge,proto3,oneof"`
}

func (*AttackRequest_Handshake) isAttackRequest_Request() {}

func (*AttackRequest_Acknowledge) isAttackRequest_Request() {}

type Handshake struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Scenarios     []*Scenario            `protobuf:"bytes,2,rep,name=scenarios,proto3" json:"scenarios,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Handshake) Reset() {
	*x = Handshake{}
	mi := &file_load_generation_system_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Handshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Handshake) ProtoMessage() {}

func (x *Handshake) ProtoReflect() protoreflect.Message {
	mi := &file_load_generation_system_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Handshake.ProtoReflect.Descriptor instead.
func (*Handshake) Descriptor() ([]byte, []int) {
	return file_load_generation_system_v1_proto_rawDescGZIP(), []int{1}
}

func (x *Handshake) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *Handshake) GetScenarios() []*Scenario {
	if x != nil {
		return x.Scenarios
	}
	return nil
}

type Scenario struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scenario) Reset() {
	*x = Scenario{}
	mi := &file_load_generation_system_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scenario) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scenario) ProtoMessage() {}

func (x *Scenario) ProtoReflect() protoreflect.Message {
	mi := &file_load_generation_system_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scenario.ProtoReflect.Descriptor instead.
func (*Scenario) Descriptor() ([]byte, []int) {
	return file_load_generation_system_v1_proto_rawDescGZIP(), []int{2}
}

func (x *Scenario) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Scenario) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type Acknowledge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Acknowledge) Reset() {
	*x = Acknowledge{}
	mi := &file_load_generation_system_v1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Acknowledge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Acknowledge) ProtoMessage() {}

func (x *Acknowledge) ProtoReflect() protoreflect.Message {
	mi := &file_load_generation_system_v1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Acknowledge.ProtoReflect.Descriptor instead.
func (*Acknowledge) Descriptor() ([]byte, []int) {
	return file_load_generation_system_v1_proto_rawDescGZIP(), []int{3}
}

type AttackResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*AttackResponse_Start
	//	*AttackResponse_Stop
	//	*AttackResponse_Kill
	Response      isAttackResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttackResponse) Reset() {
	*x = AttackResponse{}
	mi := &file_load_generation_system_v1_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttackResponse) ProtoMessage() {}

func (x *AttackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_load_generation_system_v1_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttackResponse.ProtoReflect.Descriptor instead.
func (*AttackResponse) Descriptor() ([]byte, []int) {
	return file_load_generation_system_v1_proto_rawDescGZIP(), []int{4}
}

func (x *AttackResponse) GetResponse() isAttackResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *AttackResponse) GetStart() *OperationStart {
	if x != nil {
		if x, ok := x.Response.(*AttackResponse_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *AttackResponse) GetStop() *OperationStop {
	if x != nil {
		if x, ok := x.Response.(*AttackResponse_Stop); ok {
			return x.Stop
		}
	}
	return nil
}

func (x *AttackResponse) GetKill() *OperationKill {
	if x != nil {
		if x, ok := x.Response.(*AttackResponse_Kill); ok {
			return x.Kill
		}
	}
	return nil
}

type isAttackResponse_Response interface {
	isAttackResponse_Response()
}

type AttackResponse_Start struct {
	Start *OperationStart `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type AttackResponse_Stop struct {
	Stop *OperationStop `protobuf:"bytes,2,opt,name=stop,proto3,oneof"`
}

type AttackResponse_Kill struct {
	Kill *OperationKill `protobuf:"bytes,3,opt,name=kill,proto3,oneof"`
}

func (*AttackResponse_Start) isAttackResponse_Response() {}

func (*AttackResponse_Stop) isAttackResponse_Response() {}

func (*AttackResponse_Kill) isAttackResponse_Response() {}

type OperationStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AttackId      int64                  `protobuf:"varint,2,opt,name=attack_id,json=attackId,proto3" json:"attack_id,omitempty"`
	IncrementId   int64                  `protobuf:"varint,3,opt,name=increment_id,json=incrementId,proto3" json:"increment_id,omitempty"`
	WaitTimeSec   float32                `protobuf:"fixed32,4,opt,name=wait_time_sec,json=waitTimeSec,proto3" json:"wait_time_sec,omitempty"`
	Scenarios     map[string]int64       `protobuf:"bytes,5,rep,name=scenarios,proto3" json:"scenarios,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationStart) Reset() {
	*x = OperationStart{}
	mi := &file_load_generation_system_v1_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationStart) ProtoMessage() {}

func (x *OperationStart) ProtoReflect() protoreflect.Message {
	mi := &file_load_generation_system_v1_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationStart.ProtoReflect.Descriptor instead.
func (*OperationStart) Descriptor() ([]byte, []int) {
	return file_load_generation_system_v1_proto_rawDescGZIP(), []int{5}
}

func (x *OperationStart) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OperationStart) GetAttackId() int64 {
	if x != nil {
		return x.AttackId
	}
	return 0
}

func (x *OperationStart) GetIncrementId() int64 {
	if x != nil {
		return x.IncrementId
	}
	return 0
}

func (x *OperationStart) GetWaitTimeSec() float32 {
	if x != nil {
		return x.WaitTimeSec
	}
	return 0
}

func (x *OperationStart) GetScenarios() map[string]int64 {
	if x != nil {
		return x.Scenarios
	}
	return nil
}

type OperationStop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttackId      int64                  `protobuf:"varint,1,opt,name=attack_id,json=attackId,proto3" json:"attack_id,omitempty"`
	IncrementId   *int64                 `protobuf:"varint,2,opt,name=increment_id,json=incrementId,proto3,oneof" json:"increment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationStop) Reset() {
	*x = OperationStop{}
	mi := &file_load_generation_system_v1_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationStop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationStop) ProtoMessage() {}

func (x *OperationStop) ProtoReflect() protoreflect.Message {
	mi := &file_load_generation_system_v1_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationStop.ProtoReflect.Descriptor instead.
func (*OperationStop) Descriptor() ([]byte, []int) {
	return file_load_generation_system_v1_proto_rawDescGZIP(), []int{6}
}

func (x *OperationStop) GetAttackId() int64 {
	if x != nil {
		return x.AttackId
	}
	return 0
}

func (x *OperationStop) GetIncrementId() int64 {
	if x != nil && x.IncrementId != nil {
		return *x.IncrementId
	}
	return 0
}

type OperationKill struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationKill) Reset() {
	*x = OperationKill{}
	mi := &file_load_generation_system_v1_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationKill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationKill) ProtoMessage() {}

func (x *OperationKill) ProtoReflect() protoreflect.Message {
	mi := &file_load_generation_system_v1_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationKill.ProtoReflect.Descriptor instead.
func (*OperationKill) Descriptor() ([]byte, []int) {
	return file_load_generation_system_v1_proto_rawDescGZIP(), []int{7}
}

var File_load_generation_system_v1_proto protoreflect.FileDescriptor

var file_load_generation_system_v1_proto_rawDesc = string([]byte{
	0x0a, 0x1f, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x19, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x76, 0x31, 0x22, 0xac, 0x01, 0x0a,
	0x0d, 0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x44,
	0x0a, 0x09, 0x68, 0x61, 0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x24, 0x2e, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x76, 0x31, 0x2e, 0x48, 0x61,
	0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x48, 0x00, 0x52, 0x09, 0x68, 0x61, 0x6e, 0x64, 0x73,
	0x68, 0x61, 0x6b, 0x65, 0x12, 0x4a, 0x0a, 0x0b, 0x61, 0x63, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65,
	0x64, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x6c, 0x6f, 0x61, 0x64,
	0x5f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x79, 0x73, 0x74,
	0x65, 0x6d, 0x5f, 0x76, 0x31, 0x2e, 0x41, 0x63, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67,
	0x65, 0x48, 0x00, 0x52, 0x0b, 0x61, 0x63, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65,
	0x42, 0x09, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x6b, 0x0a, 0x09, 0x48,
	0x61, 0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x6f, 0x64, 0x65,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x6f, 0x64,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x41, 0x0a, 0x09, 0x73, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69,
	0x6f, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x6c, 0x6f, 0x61, 0x64, 0x5f,
	0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x5f, 0x76, 0x31, 0x2e, 0x53, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x52, 0x09, 0x73,
	0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x73, 0x22, 0x40, 0x0a, 0x08, 0x53, 0x63, 0x65, 0x6e,
	0x61, 0x72, 0x69, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x0d, 0x0a, 0x0b, 0x41, 0x63,
	0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x22, 0xdf, 0x01, 0x0a, 0x0e, 0x41, 0x74,
	0x74, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x05,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x6c, 0x6f,
	0x61, 0x64, 0x5f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x5f, 0x76, 0x31, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x48, 0x00, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12,
	0x3e, 0x0a, 0x04, 0x73, 0x74, 0x6f, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e,
	0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x76, 0x31, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x53, 0x74, 0x6f, 0x70, 0x48, 0x00, 0x52, 0x04, 0x73, 0x74, 0x6f, 0x70, 0x12,
	0x3e, 0x0a, 0x04, 0x6b, 0x69, 0x6c, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e,
	0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x76, 0x31, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x4b, 0x69, 0x6c, 0x6c, 0x48, 0x00, 0x52, 0x04, 0x6b, 0x69, 0x6c, 0x6c, 0x42,
	0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x9a, 0x02, 0x0a, 0x0e,
	0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b,
	0x0a, 0x09, 0x61, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x61, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x69,
	0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0b, 0x69, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x22,
	0x0a, 0x0d, 0x77, 0x61, 0x69, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x65, 0x63, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b, 0x77, 0x61, 0x69, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x53,
	0x65, 0x63, 0x12, 0x56, 0x0a, 0x09, 0x73, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x73, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x38, 0x2e, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x67, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x76,
	0x31, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x2e, 0x53, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x09, 0x73, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x73, 0x1a, 0x3c, 0x0a, 0x0e, 0x53, 0x63,
	0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x65, 0x0a, 0x0d, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x6f, 0x70, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x74, 0x74,
	0x61, 0x63, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x61, 0x74,
	0x74, 0x61, 0x63, 0x6b, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0c, 0x69, 0x6e, 0x63, 0x72, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x0b,
	0x69, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x88, 0x01, 0x01, 0x42, 0x0f,
	0x0a, 0x0d, 0x5f, 0x69, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x22,
	0x0f, 0x0a, 0x0d, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4b, 0x69, 0x6c, 0x6c,
	0x32, 0x71, 0x0a, 0x06, 0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x12, 0x67, 0x0a, 0x0c, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x12, 0x28, 0x2e, 0x6c, 0x6f, 0x61,
	0x64, 0x5f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x79, 0x73,
	0x74, 0x65, 0x6d, 0x5f, 0x76, 0x31, 0x2e, 0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x67, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x76, 0x31,
	0x2e, 0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28,
	0x01, 0x30, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_load_generation_system_v1_proto_rawDescOnce sync.Once
	file_load_generation_system_v1_proto_rawDescData []byte
)

func file_load_generation_system_v1_proto_rawDescGZIP() []byte {
	file_load_generation_system_v1_proto_rawDescOnce.Do(func() {
		file_load_generation_system_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_load_generation_system_v1_proto_rawDesc), len(file_load_generation_system_v1_proto_rawDesc)))
	})
	return file_load_generation_system_v1_proto_rawDescData
}

var file_load_generation_system_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_load_generation_system_v1_proto_goTypes = []any{
	(*AttackRequest)(nil),  // 0: load_generation_system_v1.AttackRequest
	(*Handshake)(nil),      // 1: load_generation_system_v1.Handshake
	(*Scenario)(nil),       // 2: load_generation_system_v1.Scenario
	(*Acknowledge)(nil),    // 3: load_generation_system_v1.Acknowledge
	(*AttackResponse)(nil), // 4: load_generation_system_v1.AttackResponse
	(*OperationStart)(nil), // 5: load_generation_system_v1.OperationStart
	(*OperationStop)(nil),  // 6: load_generation_system_v1.OperationStop
	(*OperationKill)(nil),  // 7: load_generation_system_v1.OperationKill
	nil,                    // 8: load_generation_system_v1.OperationStart.ScenariosEntry
}
var file_load_generation_system_v1_proto_depIdxs = []int32{
	1, // 0: load_generation_system_v1.AttackRequest.handshake:type_name -> load_generation_system_v1.Handshake
	3, // 1: load_generation_system_v1.AttackRequest.acknowledge:type_name -> load_generation_system_v1.Acknowledge
	2, // 2: load_generation_system_v1.Handshake.scenarios:type_name -> load_generation_system_v1.Scenario
	5, // 3: load_generation_system_v1.AttackResponse.start:type_name -> load_generation_system_v1.OperationStart
	6, // 4: load_generation_system_v1.AttackResponse.stop:type_name -> load_generation_system_v1.OperationStop
	7, // 5: load_generation_system_v1.AttackResponse.kill:type_name -> load_generation_system_v1.OperationKill
	8, // 6: load_generation_system_v1.OperationStart.scenarios:type_name -> load_generation_system_v1.OperationStart.ScenariosEntry
	0, // 7: load_generation_system_v1.Attack.StreamAttack:input_type -> load_generation_system_v1.AttackRequest
	4, // 8: load_generation_system_v1.Attack.StreamAttack:output_type -> load_generation_system_v1.AttackResponse
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_load_generation_system_v1_proto_init() }
func file_load_generation_system_v1_proto_init() {
	if File_load_generation_system_v1_proto != nil {
		return
	}
	file_load_generation_system_v1_proto_msgTypes[0].OneofWrappers = []any{
		(*AttackRequest_Handshake)(nil),
		(*AttackRequest_Acknowledge)(nil),
	}
	file_load_generation_system_v1_proto_msgTypes[4].OneofWrappers = []any{
		(*AttackResponse_Start)(nil),
		(*AttackResponse_Stop)(nil),
		(*AttackResponse_Kill)(nil),
	}
	file_load_generation_system_v1_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_load_generation_system_v1_proto_rawDesc), len(file_load_generation_system_v1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_load_generation_system_v1_proto_goTypes,
		DependencyIndexes: file_load_generation_system_v1_proto_depIdxs,
		MessageInfos:      file_load_generation_system_v1_proto_msgTypes,
	}.Build()
	File_load_generation_system_v1_proto = out.File
	file_load_generation_system_v1_proto_goTypes = nil
	file_load_generation_system_v1_proto_depIdxs = nil
}
