// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: load_generation_system_v1.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Attack_StreamAttack_FullMethodName = "/load_generation_system_v1.Attack/StreamAttack"
)

// AttackClient is the client API for Attack service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AttackClient interface {
	StreamAttack(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AttackRequest, AttackResponse], error)
}

type attackClient struct {
	cc grpc.ClientConnInterface
}

func NewAttackClient(cc grpc.ClientConnInterface) AttackClient {
	return &attackClient{cc}
}

func (c *attackClient) StreamAttack(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AttackRequest, AttackResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Attack_ServiceDesc.Streams[0], Attack_StreamAttack_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AttackRequest, AttackResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Attack_StreamAttackClient = grpc.BidiStreamingClient[AttackRequest, AttackResponse]

// AttackServer is the server API for Attack service.
// All implementations must embed UnimplementedAttackServer
// for forward compatibility.
type AttackServer interface {
	StreamAttack(grpc.BidiStreamingServer[AttackRequest, AttackResponse]) error
	mustEmbedUnimplementedAttackServer()
}

// UnimplementedAttackServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAttackServer struct{}

func (UnimplementedAttackServer) StreamAttack(grpc.BidiStreamingServer[AttackRequest, AttackResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamAttack not implemented")
}
func (UnimplementedAttackServer) mustEmbedUnimplementedAttackServer() {}
func (UnimplementedAttackServer) testEmbeddedByValue()                {}

// UnsafeAttackServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AttackServer will
// result in compilation errors.
type UnsafeAttackServer interface {
	mustEmbedUnimplementedAttackServer()
}

func RegisterAttackServer(s grpc.ServiceRegistrar, srv AttackServer) {
	// If the following call pancis, it indicates UnimplementedAttackServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Attack_ServiceDesc, srv)
}

func _Attack_StreamAttack_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AttackServer).StreamAttack(&grpc.GenericServerStream[AttackRequest, AttackResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Attack_StreamAttackServer = grpc.BidiStreamingServer[AttackRequest, AttackResponse]

// Attack_ServiceDesc is the grpc.ServiceDesc for Attack service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Attack_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "load_generation_system_v1.Attack",
	HandlerType: (*AttackServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamAttack",
			Handler:       _Attack_StreamAttack_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "load_generation_system_v1.proto",
}
